name: Teams notification
description: Notify teams channel about the merge

inputs:
  webhook-url:
    description: 'Teams webhook URL'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@latest

    - name: Notify teams channel
      run: bun ./index.ts
      shell: bash
