name: Teams notification
description: Notify teams channel about the merge

inputs:
  webhook-url:
    description: 'Teams webhook URL'
    required: true
  title:
    description: 'Message title'
    required: true
  body:
    description: 'Message body. Can be a string or AdaptiveCard.body(https://adaptivecards.io/explorer/AdaptiveCard.html) object ]'
    required: true
  type:
    description: 'Status of message. One of "info", "warning", "error". Default is "info"'
    required: false
    default: 'info'
  actions:
    description: 'Actions to be added to the message. AdaptiveCard.actions(https://adaptivecards.io/explorer/AdaptiveCard.html) object'
    required: false
  mentionList:
    description: 'List of users to notify. Use nickname of github user "userName1" | userName2"'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2

    - name: Set not empty env vars
      shell: bash
      run: |
        set_env_var() {
          local var_name=$1
          local var_value=$2
          if [ -n "$var_value" ]; then
            echo "$var_name=$var_value" >> $GITHUB_ENV
          fi
        }
          
        set_env_var "WEBHOOK_URL" "${{ inputs.webhook-url }}"
        set_env_var "BODY" "${{ inputs.body }}"
        set_env_var "TYPE" "${{ inputs.type }}"
        set_env_var "ACTIONS" "${{ inputs.actions }}"
        set_env_var "MENTION_LIST" "${{ inputs.mentionList }}"
        set_env_var "TITLE" "${{ inputs.title }}"

    - name: Notify teams channel
      run: bun ./.github/actions/teams-notification/index.ts
      shell: bash
