name: Teams notification
description: Notify teams channel about the merge

inputs:
  webhook-url:
    description: 'Teams webhook URL'
    required: true
  body:
    description: 'Message body. Can be a string or AdaptiveCard.body(https://adaptivecards.io/explorer/AdaptiveCard.html) object ]'
    required: true
  type:
    description: 'Status of message. One of "info", "warning", "error". Default is "info"'
    required: false
    default: 'info'
  actions:
    description: 'Actions to be added to the message. AdaptiveCard.actions(https://adaptivecards.io/explorer/AdaptiveCard.html) object'
    required: false
  mentionList:
    description: 'List of users to notify. Use nickname of github user "userName1" | userName2"'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2

    - name: Notify teams channel
      run: bun ./.github/actions/teams-notification/index.ts
      env:
        WEBHOOK_URL: ${{ inputs.webhook-url }}
        BODY: ${{ inputs.body }}
        TYPE: ${{ inputs.type }}
        ACTIONS: ${{ inputs.actions }}
        MENTION_LIST: ${{ inputs.mentionList }}


      shell: bash
