name: Teams notification
description: Notify teams channel about the merge

inputs:
  webhook-url:
    description: 'Teams webhook URL'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2

    - name: Notify dedicated teams channel
      uses: jdcargile/ms-teams-notification@v1.4
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Your custom notification message
        notification-color: 17a2b8
        timezone: America/Denver
        verbose-logging: true

    - name: Notify teams channel
      run: bun ./.github/actions/teams-notification/index.ts
      env:
        WEBHOOK_URL: ${{ inputs.webhook-url }}
      shell: bash
