name: Teams notification
description: Notify teams channel about the merge

inputs:
  webhook-url:
    description: 'Teams webhook URL'
    required: true
  title:
    description: 'Message title'
    required: true
  body:
    description: 'Message body. Can be a string or AdaptiveCard.body(https://adaptivecards.io/explorer/AdaptiveCard.html) object ]'
    required: true
  type:
    description: 'Status of message. One of "info", "warning", "error". Default is "info"'
    required: false
    default: 'info'
  actions:
    description: 'Actions to be added to the message. AdaptiveCard.actions(https://adaptivecards.io/explorer/AdaptiveCard.html) object'
    required: false
  mentionList:
    description: 'List of users to notify. Use nickname of github user "userName1" | userName2"'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2

    - name: Set not empty env vars
      uses: actions/github-script@v3
      with:
        script: |
          const inputs = {
            webhookUrl: ${{inputs.webhook-url}},
            title: ${{inputs.title}},
            body: ${{inputs.body}},
            type: ${{inputs.type}},
            mentionList: ${{inputs.mentionList}},
            actions: ${{inputs.actions}}
          };
          
          core.info(`Inputs:  ${JSON.stringify(inputs)}`);

    - name: Notify teams channel
      run: bun ./.github/actions/teams-notification/index.ts
      shell: bash
