import * as core from '@actions/core';
import {getEnv, OUTPUT_NAME} from './utils';

const PR_WHICH_TRIGGERED_ACTION = core.getInput(OUTPUT_NAME.EVENT_PULL_REQUEST_INFO);
const PR_WHICH_TRIGGERED_ACTION2 = core.getState(OUTPUT_NAME.EVENT_PULL_REQUEST_INFO);

console.log('PR_WHICH_TRIGGERED_ACTION', PR_WHICH_TRIGGERED_ACTION);
console.log('PR_WHICH_TRIGGERED_ACTION2', PR_WHICH_TRIGGERED_ACTION);

console.log("env", process.env)
const PR_WHICH_TRIGGERED_ACTION3 = getEnv(OUTPUT_NAME.EVENT_PULL_REQUEST_INFO);
console.log('PR_WHICH_TRIGGERED_ACTION3', PR_WHICH_TRIGGERED_ACTION2);
