name: Revert and merge

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  update-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun ./test.ts
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: ${{ github.event.inputs.base-branch }}
          head-branch: ${{ github.event.inputs.head-branch }}
