name: Revert and merge feature

on:
  workflow_dispatch:
  pull_request:
    types: [closed, synchronize, opened, edited]

jobs:
  revert-and-merge-feature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Auto merge
        run: bun ./.github/feature-auto-merge-to-develop/revert-and-merge-feature.workflow.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
