name: Revert and merge

permissions:
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  update-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: oven-sh/setup-bun@v2
        - run: bun ./.github/feature-auto-merge-to-develop/run.ts
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
            HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
            PR_NUMBER: ${{ github.event.pull_request.number }}
