name: Revert and merge feature

on:
  workflow_dispatch:
  pull_request:
    types: [closed, opened, synchronize, edited]

defaults:
  run:
    working-directory: ./.github/workflows/revert-and-merge-feature-branch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
  HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  revert-and-merge-feature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Get info about the PR
        run: bun ./get-event-pull-request-info.step.ts

      - name: Find the last merged PR to the base branch
        run: bun ./get-last-merged-pr-to-base-branch.ts
