name: Revert and merge

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  update-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: oven-sh/setup-bun@v2
        - run: bun ./test.ts
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
            HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
