name: Revert and merge

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        run: bun ./test.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
