name: Test notification

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  test-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send notification
        uses: ./.github/actions/teams-notification
        with:
          webhook-url: https://711mediade.webhook.office.com/webhookb2/b3ff7385-d875-466c-979d-c964b95740f3@040fc3ef-6a69-42af-86d9-98f35eaede44/IncomingWebhook/dc0777bb33dc48039ddfb38edf5016ec/54b9ed1d-26b3-4848-935c-368e666000a9s
          body: Hello from GitHub Actions
          type: info
          mentionList: ${{github.actor}}
          title: Test notification

