name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate PR title
        uses: oven-sh/setup-bun@v2
        run: bun ../feature-pr-title-check/valid-pr-title.ts
